sql_db:
  image: postgres:latest
  mem_limit: 1024m
  expose:
    - "5432"
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: my_db
    POSTGRES_USER: root
    POSTGRES_PASSWORD: admin123
backend:
  volumes:
    - .:/code
  build: .
  command: bash -c "pip install --upgrade -r requirements.txt && invoke start"
  ports:
    - "8001:8001"
  links:
    - sql_db:sqldb